services:
  procraft-database:
    container_name: procraft-database
    image: postgres:15-bullseye
    ports:
    - 5432:5432
    environment:
        - POSTGRES_USER=jradmin
        - POSTGRES_PASSWORD=5o23i4oaisdjf
        - POSTGRES_DB=ProcraftDb

    volumes:
        - .pg_data:/var/lib/postgresql/pg_data

  procraftapi:
    image: devjrsoftwareengineer/procraft:v1
    container_name: procraft-api
    build:
      context: .
      dockerfile: ProcraftAPI/Dockerfile
    ports:
        - 7000:7000
    develop:
      watch:
        - path: ./
          action: rebuild
    environment:
        - SECURE_KEY="84592384askdjfaksjdq234"0980a80s98a0d9808iodfsxcvnafg;/sd]sfa[gpsdojpih8ahd]
        - PORT=7000
  