services:
  procraft-database:
    container_name: procraft-database
    image: postgres:15-bullseye
    ports:
    - 5432:5432
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}

  procraftapi:
    container_name: procraft_api
    image: devjrsoftwareengineer/procraft:v1
    build:
      context: .
      dockerfile: ProcraftAPI/Dockerfile.prod
    ports:
      - 8080:8080

    environment:
      - PORT=${PORT}
      - EMAIL_SENDER=https://sender.up.railway.app/api/send